config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  resources :users, except: [:index, :show]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :businesses, except: [:new, :edit]
    resources :reviews, only: [:index, :create, :update, :destroy]
    resources :users, only: [:show]
    resources :photos, only: [:index, :create, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, :first_name, :last_name, presence: true
  validates :password, length: { minimum: 4, allow_nil: true }
  validates :email, uniqueness: {case_sensitive: false }

  attr_reader :password
  after_initialize :ensure_session_token
  before_save :get_profile_pic_path

  has_many :reviews
  has_many :photos

  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def get_profile_pic_path
    self.profile_pic ||= "https://robohash.org/" + self.first_name.gsub(/\s+/,'') + self.last_name.gsub(/\s+/,'') + self.email.strip
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div style="color: #e6e6e6;">
  <img src="/images/sign_up.jpg" width="100%" height="100%" style="position: fixed; top: 0; z-index: -20;"/>
  <div class="row">
    <div class="col-xs-offset-5 col-xs-4">
      <h1>Sign Up</h1>
    </div>
  </div>

  <div class="row">
    <form class="form-group col-xs-4 col-xs-offset-5" action="<%= users_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="input-group">
        <label>First Name<br>
          <input class="form-control" type="text" name="user[first_name]"><br>
        </label><br>
      </div>

      <div class="input-group">
        <label>Last Name<br>
          <input class="form-control" type="text" name="user[last_name]"><br>
        </label><br>
      </div>

      <div class="input-group">
        <label>Email<br>
          <input class="form-control" name="user[email]" type="text"><br>
        </label><br>
      </div>

      <div class="input-group">
        <label>Password<br>
          <input class="form-control" name="user[password]" type="password"><br>
        </label><br>
      </div>

      <input type="submit" value="Submit" class="btn-lg btn-primary"><br>
    </form>
  </div>
</div>