config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  resources :users, except: [:index, :show]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :businesses, except: [:new, :edit]
    resources :reviews, only: [:index, :create, :update, :destroy]
    resources :users, only: [:show]
    resources :photos, only: [:index, :create, :destroy]
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  validates :name, :address, :city, :state, :zip_code, :price_range, :full_address, presence: true
  validates :address, uniqueness: {scope: [:city, :state, :zip_code]}
  validates :price_range, inclusion: 1..5
  validates :state, length: {is: 2}
  validates :zip_code, length: {is: 5}
  validates :phone_number, length: {is: 12}, allow_blank: true

  before_validation :concat_address_fields, :format_phone_number

  before_save do
    self.name.downcase!
  end

  has_many :reviews
  has_many :photos, -> {order "created_at DESC"}
  has_many :business_categories
  has_many :categories, through: :business_categories, source: :category

  def concat_address_fields
    self.full_address = "#{self.address} #{self.city} #{self.state} #{self.zip_code}".downcase
  end

  def self.filter_businesses(query, location)
    location.strip!
    location.downcase!
    query.strip!

    business_by_location = Business.where("full_address ILIKE ?", "%#{location}%")
    business_with_cats = business_by_location.joins(<<-SQL)
      LEFT OUTER JOIN
        business_categories as bc
      ON
        businesses.id = bc.business_id
      LEFT OUTER JOIN
        categories
      ON
        bc.category_id = categories.id
    SQL

    business_with_cats.where("name ILIKE ? OR category ILIKE ?", "%#{query}%", query)
  end

  def format_phone_number
    unless self.phone_number.empty?
      self.phone_number = self.phone_number.gsub(/\D/, '')
      self.phone_number.insert(3, '-')
      self.phone_number.insert(-5,'-')
    end
  end
end

app/models/business_category.rb
class BusinessCategory < ActiveRecord::Base
  validates :category_id, :business_id, presence: true
  validates :category_id, uniqueness: {scope: :business_id}

  belongs_to :category
  belongs_to :business
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :category, presence: true, uniqueness: {case_sensitive: false}

  before_save do
    self.category.capitalize!
  end

  has_many :business_categories
  has_many :businesses, through: :business_categories, source: :business
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :user_id, :business_id, :path, presence: true

  belongs_to :user
  belongs_to :business

  before_save :add_compressed

  paginates_per 4

  def add_compressed
    self.compressed = self.path.gsub("/upload/", "/upload/q_jpegmini/")
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :user_id, :business_id, :rating, presence: true
  validates :rating, inclusion: 1..5

  belongs_to :user
  belongs_to :business

  paginates_per 8
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, :first_name, :last_name, presence: true
  validates :password, length: { minimum: 4, allow_nil: true }
  validates :email, uniqueness: {case_sensitive: false }

  attr_reader :password
  after_initialize :ensure_session_token
  before_save :get_profile_pic_path

  has_many :reviews
  has_many :photos

  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def get_profile_pic_path
    self.profile_pic ||= "https://robohash.org/" + self.first_name.gsub(/\s+/,'') + self.last_name.gsub(/\s+/,'') + self.email.strip
  end
end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController
  def index
    biz_id = params[:biz_id]
    user_id = params[:user_id]
    if(biz_id)
      @photos = Photo.where(business_id: biz_id).page(params[:page])
    else
      @photos = Photo.where(user_id: user_id).page(params[:page])
    end

    render :index
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      render json: @photo
    else
      render json: @photo.errors.full_messages
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    render json: @photo
  end

  private
  def photo_params
    params.require(:photo).permit(:path, :business_id, :comment)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
    render :show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by(session_token: session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token
  end

  def sign_out
    current_user.try(:reset_session_token)
    session[:token] = nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user])

    if @user
      sign_in(@user)
      redirect_to root_url
    else
      flash[:errors] = ["Not valid login credentials"]
      redirect_to new_session_url
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
    render :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/helpers/api/businesses_helper.rb
module Api::BusinessesHelper
end

app/helpers/api/photos_helper.rb
module Api::PhotosHelper
end

app/helpers/api/reviews_helper.rb
module Api::ReviewsHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top col-xs-12">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">
        <span class="glyphicon glyphicon-home"></span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
          <li><a href="#businesses/new" id="new-biz-button">Add a Business</a></li>
        <% else %>
          <li><%= link_to "Add a Business", new_session_url %></li>
        <% end %>
        <li style="width: 125px;"></li>
      </ul>
      <form id="biz-search" class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" name="query" class="form-control" placeholder="Business/Category">
        </div>
        <div class="form-group">
          <input type="text" name="location" class="form-control" required="required" placeholder="Location">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
        <% if signed_in? %>
          <div class="navbar-right" id="logged-in">
            <%= button_to session_url, method: :delete, form_class: "navbar-right", class: "btn btn-default navbar-btn logout-button" do %>
                Sign Out
            <% end %>
            <p class="navbar-text navbar-left">
              Hi, <%= current_user.first_name + " "  + current_user.last_name[0] %>.
            </p>
          </div>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Log In", new_session_url %></li>
            <li><%= link_to "Sign Up", new_user_url %></li>
          </ul>
        <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script type="text/javascript">
  $(function(){
    $("#biz-search").submit(function(event) {
      event.preventDefault();
      var formData = $(event.currentTarget).serializeJSON();
      window.history.replaceState({}, "pley", "/?query=" + formData.query + "&location=" + formData.location);
      Backbone.history.navigate("", {trigger: true});
    });
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>pleY</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script async src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js"></script>
  <script type="text/javascript">
    window.CLOUDINARY_OPTIONS = {
      cloud_name: "<%= ENV['CLOUD_NAME'] %>",
      upload_preset: "<%= ENV['UPLOAD_PRESET'] %>",
      min_image_width: 350,
      min_image_height: 350,
      theme: "minimal"
    };
  </script>
</head>
<body>

  <%= render template: "layouts/_navigation_bar" %>

  <% if flash[:errors] %>
    <div class="alert alert-danger" role="alert" style="margin-top:50px; text-align: center;">
      <%= flash[:errors].join("<br>").html_safe %>
    </div>
  <% end %>

  <div id="site-content">
    <%= yield %>
  </div>
  <div class="footer"></div>
  <div style="clear:both;"></div>
  <%= javascript_include_tag "lightbox.js" %>
</body>
</html>